name: Deploy

on:
  push:
    branches:
      - master
    paths:
      - !*.md

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: |
          yarn install
          yarn lint
          yarn build
      - uses: actions/gcloud/auth@master
        env:
          GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
      - uses: actions/gcloud/cli@master
        with:
          args: >
            functions
            deploy
            hello
            --entry-point=handler
            --project=${{ secrets.GCLOUD_PROJECT_ID }}
            --runtime=nodejs10
            --source=dist
            --trigger-http
