name: Test gcloud

on: push

jobs:
  test-gcloud:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/gcloud/auth@master
        env:
          GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
      - uses: actions/gcloud/cli@master
        with:
          args: info
